const mongoose = require('mongoose');

const ProductTypeSettingSchema = new mongoose.Schema({
    productType: { type: String, required: false },
    category: { type: String, required: false },
    brand: { type: String, required: false },
    productDescription: { type: String, required: false },
    identifierCodeType: { type: String, required: false },
    identifierCode: { type: String, required: false },
    colorTypeVariantimagePrice: { type: String, required: false },
    packageWeight: { type: Number, required: false },
    packageLength: { type: Number, required: false },
    packageWidth: { type: Number, required: false },
    packageHeight: { type: Number, required: false },
    deliveryOptions: { type: String, required: false },
    quantityinALEASEWILLIS: { type: Number, required: false },
    quantityinCORNELLHODGES: { type: Number, required: false },
    sizeChart: { type: String, required: false },
    material: { type: String, required: false },
    pattern: { type: String, required: false },
    neckline: { type: String, required: false },
    clothingLength: { type: String, required: false },
    sleeveLength: { type: String, required: false },
    season: { type: String, required: false },
    occasion: { type: String, required: false },
    style: { type: String, required: false },
    feature: { type: String, required: false },
    shape: { type: String, required: false },
    scent: { type: String, required: false },
    setting: { type: String, required: false },
    use: { type: String, required: false },
    installment: { type: String, required: false },
    fit: { type: String, required: false },
    stretch: { type: String, required: false },
    careInstructions: { type: String, required: false },
    waistHeight: { type: String, required: false },
    volume: { type: String, required: false },
    magnets: { type: String, required: false },
    manufacturingTechnique: { type: String, required: false },
    ageGroup: { type: String, required: false },
    battery: { type: String, required: false },
    bPAFree: { type: String, required: false },
    otherDangerousGoodsorHazardousMaterials: { type: String, required: false },
    cAProp65Carcinogens: { type: String, required: false },
    carcinogen: { type: String, required: false },
    cAProp65ReproChems: { type: String, required: false },
    reprotoxicChemicals: { type: String, required: false },
    containsBatteriesorCells: { type: String, required: false },
    batteryType: { type: String, required: false },
    howBatteriesArePacked: { type: String, required: false },
    numberofBatteriesorcells: { type: Number, required: false },
    batteryorCellCapacityinWh: { type: Number, required: false },
    batteryorCellCapacityingrams: { type: Number, required: false },
    batteryorCellWeightingrams: { type: Number, required: false },
    flammableLiquid: { type: String, required: false },
    flammableLiquidVolumeinml: { type: Number, required: false },
    aerosols: { type: String, required: false },
    aerosolLiquidVolumeinml: { type: Number, required: false },
    safetyDataSheetforflammablematerials: { type: String, required: false },
    safetyDataSheetforproductswithbatteries: { type: String, required: false },
    safetyDataSheetforaerosolproducts: { type: String, required: false },
    safetyDataSheetforotherdangerousgoodsorhazardousmaterials: { type: String, required: false }
});

module.exports = mongoose.model('ProductTypeSetting', ProductTypeSettingSchema);
